const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const context = { console, globalThis: {}, URL, crypto: require('crypto').webcrypto };
context.globalThis = context;
vm.createContext(context);
['models.js', 'template-engine.js'].forEach((file) => vm.runInContext(fs.readFileSync(file, 'utf8'), context, { filename: file }));
const M = context.AppModels, T = context.TemplateEngine;
assert.equal(M.slugify('House Flipper: Home Design'), 'house-flipper-home-design');
assert.equal(M.gerarNomeArquivo('House Flipper: Home Design', '1.670', 'MOD'), 'house-flipper-home-design-v1.670-mod.apk');
const rendered = T.render('{{nome}} {{#if mod}}MOD{{/if}} {{#each screenshots}}<img src="{{this}}" alt="{{../nome}}">{{/each}}', { nome: 'A & B', mod: 'sim', screenshots: ['https://a.test/x.png'] });
assert(rendered.includes('A &amp; B MOD'));
assert(rendered.includes('alt="A &amp; B"'));
const report = T.analisar('{{nome}}{{versao}}{{descricaoHtml}}{{linkDownload}}{{coisaEstranha}}');
assert.deepEqual(Array.from(report.ausentes), []);
assert.deepEqual(Array.from(report.desconhecidas), ['coisaEstranha']);
const draft = M.novaPostagem({ nome: 'Teste', versao: '2', mod: 'x' });
assert(draft.id && draft.nomeArquivo === 'teste-v2-mod.apk');
const templatePadrao = fs.readFileSync('template.html', 'utf8');
const templateReport = T.analisar(templatePadrao);
assert.deepEqual(Array.from(templateReport.ausentes), []);
const htmlPadrao = T.render(templatePadrao, { postId:'post-test', nome:'Jogo Teste', versao:'1.2', descricaoHtml:'<p>Descrição</p>', linkDownload:'https://example.com/a.apk', downloadHref:'https://example.com/a.apk', downloadEstado:'', downloadMensagem:'', icone:'https://example.com/i.png', categoria:'Ação', avaliacao:'4.7', sistema:'7.0', dataAtualizacao:'15/07/2026', mod:'MOD', recursosModHtml:'<div>Recurso</div>', screenshots:['https://example.com/s.png'], nomeArquivo:'jogo-v1.2-mod.apk' });
assert(htmlPadrao.includes('mod-action-download'));
assert(htmlPadrao.includes('Jogo Teste'));
assert(!htmlPadrao.includes('{{nome}}'));
console.log('Todos os testes passaram.');
